//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string TheLoai { get; set; }
        public string BookName { get; set; }
        public string TacGia { get; set; }
        public string Anh { get; set; }
        public System.DateTime NgayPH { get; set; }
        public string Mota { get; set; }
        public int Gia { get; set; }
    }
}
